# .github/workflows/deploy-password.yml
name: Deploy via password

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS (using password)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/massimo/apps/demo-app  
            chmod +x /home/massimo/apps/demo-app/deploy.sh
            ./deploy.sh
